version: '3.1'
services:

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/app/
      - /app/node_modules
    env_file: ./backend/.env
    ports:
      - 4000:4000
    expose:
      - 4000
    restart: always

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    volumes:
      - ./postgres/db-data:/var/lib/postgresql/data
      - ./postgres/db:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      POSTGRES_DB: test-task-db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password